### ISSUE TITLE
Questions regarding MultiZone Cortex M configurations

### ISSUE THREAD

**Issue by sumasree98** [hex-five/multizone-sdk-arm#1]
Hi!
I am trying out the MultiZone Cortex M product on the RA6M3 renesas board, and I had a few questions regarding that. 

1. I was trying to change the system clock speed by setting the ICLK to 1/8 (30 MHz) in the configuration.xml file in e2studio. However, even after I set it and change everything, the clock speed doesn't actually change. I was wondering if it was because of MultiZone. Is MultiZone setting a clock speed on its own? Are the developers not allowed to set their own clock speed?
2. I know that most low level Cortex M processors do not have an internal cache. However, this product is supposed to run even on processors such as the Cortex M33. Therefore, I wanted to ask if there is any precaution being taken to prevent cache side channel attacks? For example, is the cache cleared when a context switch happens between zones?

Thank you!

**Comment by cgarlati** [comment]
Hi @sumasree98,

Thank you for your questions!

_>>> Is MultiZone setting a clock speed on its own?_
No. By design, MultiZone trusted code base is kept intentionally minimal to reduce attack surface and to allow for formal verification.

_>>> Are the developers not allowed to set their own clock speed?_
Developers are allowed to set any system configuration of choice with the use of the --boot param.

See [User Manual](https://github.com/hex-five/multizone-sdk-arm/blob/master/manual.pdf) page 37:

```
The optional --boot parameter allows to specify an arbitrary binary file (.HEX or .ELF) to be
executed at system boot before starting the zones threads. This code may be provided as part of the Board
Support Package or generated dynamically by various IDE tools. It is intended to bring up and configure
hardware blocks like PLLs, IO, IRQs/IC, watchdog, etc.
``` 

See a Renesas example at [MultiZone IoT Firmware e² Studio project](https://hex-five.com/multizone-trusted-firmware-for-cortex-m/)

_>>> is there is any precaution being taken to prevent cache side channel attacks?_
Not in this generic evaluation version. Cache and other microarchitectural countermeasures are device specific and implemented only in commercially licensed versions of MultiZone.

**Comment by sumasree98** [comment]
Thank you!
