### ISSUE TITLE
MultiZone configuration tick time

### ISSUE THREAD

**Issue by sumasree98** [hex-five/multizone-sdk-arm#2]
Hello,
Using the tick parameter in the multizone.cfg file, if I set the tick time to be 10 ms, does that mean that each zone is run for 10 ms completely before being interrupted, or is the context switch (or some other work) done within that 10 ms?
And is a zone interrupted in any way by the kernel before it completely executes for 10 ms?

Thank you!

**Comment by cgarlati** [comment]
Suma:

The **tick** configuration parameter drives the preemptive scheduler. It specifies the maximum amount of time in
milliseconds that each zone can hold the CPU. If a zone exceeds this limit, the preemptive scheduler
suspends the zone execution and moves to the next according to a fair round robin schema. If the tick
value is set to 0, the scheduler policy becomes fully cooperative: zones must explicitly yield execution via
MZONE_YIELD() or MZONE_WFI() APIs for the other zones to run.

_>>> if I set the tick time to be 10 ms, does that mean that each zone is run for 10 ms completely before being interrupted?_
10ms is the max time if there are other zones ready. Otherwise there is no interruption.

_>>> is a zone interrupted in any way by the kernel before it completely executes for 10 ms?_
No. MultiZone kernel is tickless to support low power suspend states - i.e. battery operated devices.

Cesare
